### ISSUE TITLE
Question about updates

### ISSUE THREAD

**Issue by Macleykun** [oijkn/pihole-doh-dot#1]
Heya!
Thanks for making this image :) it really made it easy to setup pihole with DoH/DoT!

I did notice it was a bit out of date, how do you usually update the image? You use a CI/CD for this?

If not, perhaps i can help with this :) ?

**Comment by oijkn** [comment]
I don't use CI/CD, usually I build the docker locally then push it into the hub.

I haven't updated this project in a while because I'm trying to do the same thing with AdGuard Home.

**Comment by Macleykun** [comment]
> I don't use CI/CD, usually I build the docker locally then push it into the hub.
> 
> I haven't updated this project in a while because I'm trying to do the same thing with AdGuard Home.

Aaaah I see, is adguard better? Will the pi one be deprecated?

**Comment by oijkn** [comment]
AdGuard Home vs Pi-Hole ?

See full details in Adguard Home [wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Comparison#comparing-adguard-home-to-other-solutions)

**Comment by Macleykun** [comment]
aaah i see! now i understand why adguard is more prefered!
I'll move over to that one instead :) thanks!
